version: '3.8'
services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      PGHOST: ec2-52-21-136-176.compute-1.amazonaws.com
      POSTGRES_DB: dd4k0rij05bmum
      PGUSER: hbuppbrssflnpu
      PGPASSWORD: 0864babc2c22356d00c3b7ecc10cc51144e19593cd6c59c69b795aff54022fe4
    #volumes:
    #  - "${PWD}/data/initdb/:/docker-entrypoint-initdb.d/"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - db
